const teacherList = [
  { name: "Jon Agriesti", mail: "jon_agriesti_at_hboe.org" },
  { name: "Thad Apel", mail: "thad_apel_at_hboe.org" },

  { name: "Betsy Barber", mail: "betsy_barber_at_hboe.org" },
  { name: "Lisa Barber", mail: "lisa_barber_at_hboe.org" },
  { name: "Jennifer Beatty", mail: "jennifer_beatty_at_hboe.org" },
  { name: "Eric Bell", mail: "eric_bell_at_hboe.org" },
  { name: "Evan Bell", mail: "evan_bell_at_hboe.org" },
  { name: "Monica Bell", mail: "monica_bell_at_hboe.org" },
  { name: "Judy Biddinger", mail: "judy_biddinger_at_hboe.org" },
  { name: "Rebecca Biller", mail: "rebecca_biller_at_hboe.org" },
  { name: "Beth Boza", mail: "beth_boza_at_hboe.org" },

  { name: "Kristopher Camp", mail: "kristopher_camp_at_hboe.org" },
  { name: "Sabine Canty", mail: "sabine_canty_at_hboe.org" },
  { name: "Dave Carter", mail: "dave_carter_at_hboe.org" },
  { name: "Amy Case", mail: "amy_case_at_hboe.org" },
  { name: "Jim Caudill", mail: "jim_caudill_at_hboe.org" },
  { name: "Chris Chase", mail: "chris_chase_at_hboe.org" },
  { name: "Tyler Chumita", mail: "tyler_chumita_at_hboe.org" },
  { name: "Richard Chute", mail: "Richard_chute_at_hboe.org" },
  { name: "Sara Clipson", mail: "sara_clipson_at_hboe.org" },
  { name: "Lizzy Clancy", mail: "Lizzy_clancy_at_hboe.org" },
  { name: "Jenna Crawford", mail: "jenna_crawford_at_hboe.org" },
  { name: "Nick Crawford", mail: "nicholas_crawford_at_hboe.org" },
  { name: "Rachel Creamer", mail: "rachel_creamer_at_hboe.org" },
  { name: "Lucia Culley", mail: "lucia_culley_at_hboe.org" },
  { name: "Amy Curtiss-Kast", mail: "amy_curtiss-kast_at_hboe.org" },

  { name: "Maura Danko", mail: "maura_danko_at_hboe.org" },
  { name: "Connie DelaCruz", mail: "connie_delacruz_at_hboe.org" },
  { name: "Tim Dellapina", mail: "tim_delapina_at_hboe.org" },
  { name: "Brian Dickmann", mail: "Brian_dickmann_at_hboe.org" },
  { name: "Scott Dietrich", mail: "scott_dietrich_at_hboe.org" },
  { name: "Stephanie Dietrich", mail: "stephanie_dietrich_at_hboe.org" },

  { name: "Amy Ebenezer", mail: "amy_ebenezer_at_hboe.org" },
  { name: "Elsayed Elmasry", mail: "elsayed_elmasry_at_hboe.org" },

  { name: "Laurie Fair", mail: "laurie_fair_at_hboe.org" },
  { name: "Leslye Federer", mail: "leslye_federer_at_hboe.org" },
  { name: "Carrie Ferreri", mail: "carrie_ferreri_at_hboe.org" },
  { name: "Jonathan Figel", mail: "jon_figel_at_hboe.org" },
  { name: "Norb Fischer", mail: "norb_fischer_at_hboe.org" },
  { name: "Elissa Foster", mail: "elissa_foster_at_hboe.org" },
  { name: "Jackie Fowler", mail: "jackie_fowler_at_hboe.org" },
  { name: "Chris Fugitt", mail: "chris_fugitt_at_hboe.org" },

  { name: "Nathan Geers", mail: "nathan_geers_at_hboe.org" },
  { name: "Amber Geiser", mail: "amber_geiser_at_hboe.org" },
  { name: "Hannah Gerken", mail: "hannan_gerken_at_hboe.org" },
  { name: "Erica Golden", mail: "erica_golden_at_hboe.org" },
  { name: "Nancy Gordon", mail: "nancy_gordon_at_hboe.org" },
  { name: "Stephanie Grieble", mail: "stephanie_grieble_at_hboe.org" },
  { name: "Gail Griffith", mail: "gail_griffith_at_hboe.org" },
  { name: "Michelle Griffith", mail: "michelle_griffith_at_hboe.org" },

  { name: "Yvonne Haight", mail: "yvonne_haight_at_hboe.org" },
  { name: "Lauren Hall", mail: "lauren_hall_at_hboe.org" },
  { name: "Pat Hall", mail: "pat_hall_at_hboe.org" },
  { name: "Andrew Helmlinger", mail: "andrew_helmlinger_at_hboe.org" },
  { name: "Nikki Henkel", mail: "nikki_henkel_at_hboe.org" },
  { name: "Lauren Hickson", mail: "lauren_hickson_at_hboe.org" },
  { name: "Ellen Holland", mail: "ellen_holland_at_hboe.org" },
  { name: "Kristina Hooper", mail: "kristina_hooper_at_hboe.org" },
  { name: "Alex Huffman", mail: "alex_huffman_at_hboe.org" },
  { name: "Jody Hume", mail: "jody_hume_at_hboe.org" },

  { name: "Nicholas James", mail: "nicholas_james_at_hboe.org" },
  { name: "Jeremy Jones", mail: "jeremy_jones_at_hboe.org" },
  { name: "Rich Jones", mail: "rich_jones_at_hboe.org" },

  {
    name: "Sivashree Kanagasabapathy",
    mail: "siva_kanagasabapathy_at_hboe.org",
  },
  { name: "Cathy Kane", mail: "cathy_kane_at_hboe.org" },
  { name: "Jennifer Kelly", mail: "jennifer_kelly_at_hboe.org" },
  { name: "Hollie Ketcham", mail: "hollie_ketcham_at_hboe.org" },
  { name: "Genny Kinney", mail: "genny_kinney_at_hboe.org" },
  { name: "Andrew Kisner", mail: "andrew_kisner_at_hboe.org" },
  { name: "Kim Kisner", mail: "kim_kisner_at_hboe.org" },
  { name: "Jeremy Kozman", mail: "jeremy_kozman_at_hboe.org" },
  { name: "Allison Kruder", mail: "Allison_kruder_at_hboe.org" },

  { name: "Cindy Large", mail: "cindy_large_at_hboe.org" },
  { name: "Hannah Lewis", mail: "hannah_lewis_at_hboe.org" },
  { name: "Peggy Limbacher", mail: "peggy_limbacher_at_hboe.org" },
  { name: "Craig Lohmann", mail: "craig_lohmann_at_hboe.org" },
  { name: "Chris Ludban", mail: "chris_ludban_at_hboe.org" },

  { name: "Crystal Madigan", mail: "crystal_madigan_at_hboe.org" },
  { name: "Elizabeth Martin", mail: "elizabeth_martin_at_hboe.org" },
  { name: "Laura Martin", mail: "laura_martin_at_hboe.org" },
  { name: "Mike Martin", mail: "mike_martin_at_hboe.org" },
  { name: "Christopher Maul", mail: "chris_maul_at_hboe.org" },
  { name: "Kaylee McClaskie", mail: "kaylee_mcclaskie_at_hboe.org" },
  { name: "Laura McDaniels", mail: "laura_mcdaniels_at_hboe.org" },
  { name: "Daniel McDuffie", mail: "daniel_mcduffie_at_hboe.org" },
  { name: "Theresa Meach", mail: "theresa_meach_at_hboe.org" },
  { name: "Amy Messick", mail: "amy_messick_at_hboe.org" },
  { name: "Matt Middleton", mail: "matt_middleton_at_hboe.org" },
  { name: "Brett Miller", mail: "brett_miller_at_hboe.org" },
  { name: "Jennifer Miller", mail: "jennifer_miller_at_hboe.org" },
  { name: "Steven Mitchell", mail: "steven_mitchell_at_hboe.org" },
  { name: "Sahar Mohamed", mail: "sahar_mohamed_at_hboe.org" },
  { name: "Janet Monseur-Durr", mail: "janet_monseur-durr_at_hboe.org" },
  { name: "Tiffany Montgomery", mail: "tiffany_montgomery_at_hboe.org" },
  { name: "Jennifer Moore", mail: "jennifer_moore_at_hboe.org" },
  { name: "Shawn Morris", mail: "shawn_morris_at_hboe.org" },
  { name: "Neal Myers", mail: "neal_myers_at_hboe.org" },

  { name: "Allison Newman", mail: "allison_newman_at_hboe.org" },
  { name: "Scott Nickel", mail: "scott_nickel_at_hboe.org" },

  { name: "April Obrist", mail: "april_obrist_at_hboe.org" },
  { name: "Adam Olsheski", mail: "adam_olsheski_at_hboe.org" },
  { name: "Rachel Olsheski", mail: "rachel_olsheski_at_hboe.org" },
  { name: "Andrew Ozbolt", mail: "andrew_ozbolt_at_hboe.org" },

  { name: "Shawn Papp", mail: "shawn_papp_at_hboe.org" },
  { name: "Ericka Payne", mail: "ericka_payne_at_hboe.org" },
  { name: "Josh Penzone", mail: "josh_penzone_at_hboe.org" },
  { name: "Hannah Phillip", mail: "hannah_phillip_at_hboe.org" },
  { name: "Cory Poe", mail: "cory_poe_at_hboe.org" },
  { name: "Gina Pullin", mail: "gina_pullin_at_hboe.org" },

  { name: "Rosalyn Quaranta", mail: "rosalyn_quaranta_at_hboe.org" },

  { name: "Jennifer Rambin", mail: "jennifer_rambin_at_hboe.org" },
  { name: "Connie Rasmussen", mail: "connie_rasmussen_at_hboe.org" },
  { name: "Max Ratliff", mail: "max_ratliff_at_hboe.org" },
  { name: "Brooke Rausch", mail: "brooke_rausch_at_hboe.org" },
  { name: "Griffin Reed", mail: "griffin_reed_at_hboe.org" },
  { name: "Mallory Reed", mail: "mallory_reed_at_hboe.org" },
  { name: "Kyle Reichle", mail: "kyle_reichle_at_hboe.org" },
  { name: "Brenda Ribble", mail: "brenda_ribble_at_hboe.org" },
  { name: "David Rickert", mail: "david_rickert_at_hboe.org" },
  { name: "John Riegel", mail: "john_riegel_at_hboe.org" },
  { name: "Justin Riley", mail: "justin_riley_at_hboe.org" },
  { name: "Glen Rogers", mail: "glen_rogers_at_hboe.org" },
  { name: "Blake Ryan", mail: "blake_ryan_at_hboe.org" },
  {
    name: "Bridget Ryan",
    mail: "bridget_ebenhack_at_hboe.org, bridget_ryan_at_hboe.org",
  },

  { name: "Jeff Sanderson", mail: "jeff_sanderson_at_hboe.org" },
  { name: "John Santagata", mail: "john_santagata_at_hboe.org" },
  { name: "Amy Shafer", mail: "amy_shafer_at_hboe.org" },
  { name: "Kelly Sherman", mail: "kelly_sherman_at_hboe.org" },
  { name: "Richard Shoemaker", mail: "richard_shoemaker_at_hboe.org" },
  { name: "Alyssa Sidders", mail: "alyssa_sidders_at_hboe.org" },
  { name: "Katie Sims", mail: "katie_sims_at_hboe.org" },
  { name: "Morgan Skaff", mail: "morgan_skaff_at_hboe.org" },
  { name: "Jay Smith", mail: "jay_smith_at_hboe.org" },
  { name: "Stephanie Stauffer", mail: "stephanie_french_at_hboe.org" },
  { name: "Maria Stead", mail: "maria_stead_at_hboe.org" },
  { name: "Joshua Stephens", mail: "joshua_stephens_at_hboe.org" },
  { name: "Hannah Sterman", mail: "hannah_sterman_at_hboe.org" },
  { name: "Kristi Stewart", mail: "kristi_stewart_at_hboe.org" },
   { name: "Kim Sutton", mail: "kim_sutton_at_hboe.org" },
  { name: "Nikki Sweder", mail: "nikki_sweder_at_hboe.org" },

  { name: "Kuei-Fang Tai", mail: "kuei-fang_tai_at_hboe.org" },
  { name: "Clay Trubiano", mail: "clay_trubiano_at_hboe.org" },

  { name: "Darice Veri", mail: "darice_veri_at_hboe.org" },
  { name: "Brian Vogt", mail: "brian_vogt_at_hboe.org" },
  { name: "Scott Volzer", mail: "scott_volzer_at_hboe.org" },

  { name: "D'Ette Wagar", mail: "dette_wagar_at_hboe.org" },
  { name: "Krista Wagner", mail: "krista_wagner_at_hboe.org" },
  { name: "Steven Watts", mail: "steven_watts_at_hboe.org" },
  { name: "Dena Way", mail: "dena_way_at_hboe.org" },
  { name: "Michael Weer", mail: "michael_weer_at_hboe.org" },
  { name: "Shirley Wehr", mail: "shirley_wehr_at_hboe.org" },
  { name: "Margie White", mail: "marjorie_white_at_hboe.org" },
  { name: "Chelsea Whitehouse", mail: "chelsea_whitehouse_at_hboe.org" },
  { name: "Anne Wilcox", mail: "anne_wilcox_at_hboe.org" },
  { name: "Julie Wolfe", mail: "Julie_Wolfe_at_hboe.org" },
  { name: "Tom Woodford", mail: "tom_woodford_at_hboe.org" },
  { name: "Melissa Wright", mail: "melissa_wright_at_hboe.org" },

  { name: "Stanley Zody", mail: "stan_zody_at_hboe.org" },
];
